version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: SimbrionRoot321!
      MYSQL_DATABASE: sra_db
    ports:
      - "3307:3307"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    image: sra-app
    container_name: sra-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sra_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SimbrionRoot321!
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  mysql-data: